## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

EIN                                      NAME APPLICATION_TYPE  \
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB              T10   
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR               T3   
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS               T5   
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION               T3   
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT               T3   

        AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS  \
0       Independent          C1000    ProductDev   Association       1   
1       Independent          C2000  Preservation  Co-operative       1   
2  CompanySponsored          C3000    ProductDev   Association       1   
3  CompanySponsored          C2000  Preservation         Trust       1   
4       Independent          C1000     Heathcare         Trust       1   

      INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0              0                      N     5000              1  
1         1-9999                      N   108590              1  
2              0                      N     5000              0  
3    10000-24999                      N     6692              1  
4  100000-499999                      N   142590              1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df=application_df.drop(['EIN','NAME'],axis=1)

In [3]:
# Determine the number of unique values in each column.
unique_value_counts = application_df.nunique()
print(unique_value_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64


In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64


In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 10
top_application_types = application_type_counts[:cutoff_value].index.tolist()
application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].apply(lambda x: x if x in top_application_types else 'Other')
application_types_to_replace = ['Other'] + top_application_types
print(application_types_to_replace)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

['Other', 'T3', 'T4', 'T6', 'T5', 'T19', 'T8', 'T7', 'T10', 'T9', 'T13']


Other    34299
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...  
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64


In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_greater_1 = classification_counts[classification_counts > 1]
print(classification_counts_greater_1)


C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64


In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 10
top_classifications = classification_counts[:cutoff_value].index.tolist()
application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].apply(lambda x: x if x in top_classifications else 'Other')
classifications_to_replace = ['Other'] + top_classifications

print(classifications_to_replace)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

['Other', 'C1000', 'C2000', 'C1200', 'C3000', 'C2100', 'C7000', 'C1700', 'C4000', 'C5000', 'C1270']


Other    34299
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()


STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other  \
0       1     5000              1                     1.0   
1       1   108590              1                     1.0   
2       1     5000              0                     1.0   
3       1     6692              1                     1.0   
4       1   142590              1                     1.0   

   AFFILIATION_CompanySponsored  AFFILIATION_Family/Parent  \
0                           0.0                        0.0   
1                           0.0                        0.0   
2                           1.0                        0.0   
3                           1.0                        0.0   
4                           0.0                        0.0   

   AFFILIATION_Independent  AFFILIATION_National  AFFILIATION_Other  \
0                      1.0                   0.0                0.0   
1                      1.0                   0.0                0.0   
2                      0.0                   0.0                0.0   
3                      0.0                   0.0                0.0   
4                      1.0                   0.0                0.0   

   AFFILIATION_Regional  ...  INCOME_AMT_1-9999  INCOME_AMT_10000-24999  \
0                   0.0  ...                0.0                     0.0   
1                   0.0  ...                1.0                     0.0   
2                   0.0  ...                0.0                     0.0   
3                   0.0  ...                0.0                     1.0   
4                   0.0  ...                0.0                     0.0   

   INCOME_AMT_100000-499999  INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  \
0                       0.0                 0.0               0.0   
1                       0.0                 0.0               0.0   
2                       0.0                 0.0               0.0   
3                       0.0                 0.0               0.0   
4                       1.0                 0.0               0.0   

   INCOME_AMT_25000-99999  INCOME_AMT_50M+  INCOME_AMT_5M-10M  \
0                     0.0              0.0                0.0   
1                     0.0              0.0                0.0   
2                     0.0              0.0                0.0   
3                     0.0              0.0                0.0   
4                     0.0              0.0                0.0   

   SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y  
0                       1.0                       0.0  
1                       1.0                       0.0  
2                       1.0                       0.0  
3                       1.0                       0.0  
4                       1.0                       0.0  

[5 rows x 31 columns]

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
y = application_df['IS_SUCCESSFUL'].values



# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
print("Training set (X_train):")
print(X_train)
print("\nTesting set (X_test):")
print(X_test)
print("\nTraining labels (y_train):")
print(y_train)
print("\nTesting labels (y_test):")
print(y_test)


Training set (X_train):
[[1.e+00 5.e+03 1.e+00 ... 0.e+00 1.e+00 0.e+00]
 [1.e+00 5.e+03 1.e+00 ... 0.e+00 1.e+00 0.e+00]
 [1.e+00 5.e+03 1.e+00 ... 0.e+00 1.e+00 0.e+00]
 ...
 [1.e+00 5.e+03 1.e+00 ... 0.e+00 1.e+00 0.e+00]
 [1.e+00 5.e+03 1.e+00 ... 0.e+00 1.e+00 0.e+00]
 [1.e+00 5.e+03 1.e+00 ... 0.e+00 1.e+00 0.e+00]]

Testing set (X_test):
[[1.0000e+00 5.0087e+04 1.0000e+00 ... 0.0000e+00 1.0000e+00 0.0000e+00]
 [1.0000e+00 5.0000e+03 1.0000e+00 ... 0.0000e+00 1.0000e+00 0.0000e+00]
 [1.0000e+00 5.0000e+03 1.0000e+00 ... 0.0000e+00 1.0000e+00 0.0000e+00]
 ...
 [1.0000e+00 5.0000e+03 1.0000e+00 ... 0.0000e+00 1.0000e+00 0.0000e+00]
 [1.0000e+00 5.7522e+04 1.0000e+00 ... 0.0000e+00 1.0000e+00 0.0000e+00]
 [1.0000e+00 5.0000e+03 1.0000e+00 ... 0.0000e+00 1.0000e+00 0.0000e+00]]

Training labels (y_train):
[0 1 1 ... 0 1 0]

Testing labels (y_test):
[1 1 0 ... 1 0 0]


In [12]:

Scaler = StandardScaler()


# Fit the StandardScaler

X_scaler= Scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train_scaled.shape[1]
hidden_nodes_layer1=7
hidden_nodes_layer2=14

nn = tf.keras.models.Sequential()



# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 7)                 217       
                                                                 
 dense_1 (Dense)             (None, 14)                112       
                                                                 
 dense_2 (Dense)             (None, 1)                 15        
                                                                 
Total params: 344 (1.34 KB)
Trainable params: 344 (1.34 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [15]:
# Train the model

fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 1s 583us/step - loss: 0.6560 - accuracy: 0.6420 - val_loss: 0.6015 - val_accuracy: 0.6893
Epoch 2/100
684/684 [==============================] - 0s 486us/step - loss: 0.6106 - accuracy: 0.6876 - val_loss: 0.5932 - val_accuracy: 0.7074
Epoch 3/100
684/684 [==============================] - 0s 518us/step - loss: 0.6065 - accuracy: 0.6956 - val_loss: 0.5906 - val_accuracy: 0.7061
Epoch 4/100
684/684 [==============================] - 0s 481us/step - loss: 0.6049 - accuracy: 0.6953 - val_loss: 0.5902 - val_accuracy: 0.7090
Epoch 5/100
684/684 [==============================] - 0s 483us/step - loss: 0.6042 - accuracy: 0.6953 - val_loss: 0.5896 - val_accuracy: 0.7116
Epoch 6/100
684/684 [==============================] - 0s 482us/step - loss: 0.6032 - accuracy: 0.6957 - val_loss: 0.5893 - val_accuracy: 0.7116
Epoch 7/100
684/684 [==============================] - 0s 501us/step - loss: 0.6026 - accuracy: 0.6952 - val_loss: 0.5883 - val_ac

684/684 [==============================] - 0s 479us/step - loss: 0.5995 - accuracy: 0.6985 - val_loss: 0.5878 - val_accuracy: 0.7116
Epoch 58/100
684/684 [==============================] - 0s 487us/step - loss: 0.5992 - accuracy: 0.6984 - val_loss: 0.5899 - val_accuracy: 0.7113
Epoch 59/100
684/684 [==============================] - 0s 477us/step - loss: 0.5992 - accuracy: 0.6989 - val_loss: 0.5882 - val_accuracy: 0.7124
Epoch 60/100
684/684 [==============================] - 0s 486us/step - loss: 0.5991 - accuracy: 0.6987 - val_loss: 0.5895 - val_accuracy: 0.7059
Epoch 61/100
684/684 [==============================] - 0s 486us/step - loss: 0.5993 - accuracy: 0.7001 - val_loss: 0.5879 - val_accuracy: 0.7100
Epoch 62/100
684/684 [==============================] - 0s 478us/step - loss: 0.5992 - accuracy: 0.6995 - val_loss: 0.5882 - val_accuracy: 0.7080
Epoch 63/100
684/684 [==============================] - 0s 475us/step - loss: 0.5993 - accuracy: 0.6990 - val_loss: 0.5894 - val_accuracy

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6023 - accuracy: 0.6953 - 79ms/epoch - 295us/step
Loss: 0.602347731590271, Accuracy: 0.6952769756317139


In [17]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')


/Users/sophieyoon/anaconda3/lib/python3.10/site-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
